[package]
version = "0.1.0"
edition = "2018"

# Either `license` or `license-file` to be set
# ref: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
license = "MIT OR Apache-2.0"

name = "zdict"
description = "Look up words via online dictionaries"
# Default use `.md` and not support extension `.rst`
# ref: https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field
#readme = "README.md"

#keywords = []
#categories = []

# Will automatically link to the corresponding docs.rs page if not given.
# Must set it because docs.rs only render libraries.
# ref: https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field
#documentation = ""
#homepage = ""
#repository = ""

[dependencies]
clap = { version = "3.0.0-beta.4", features = ["yaml"] }

#hyper = { version = "*", features = ["full"] }
#tokio = { version = "*", features = ["full"] }  # require "full" by `tokio::main`
reqwest = { version = "*", features = ["blocking"] }

html5ever = "*"
kuchiki = "*"

#serde = { version = "*", features = ["derive"] }
serde_json = "*"
